# Generated by Django 2.2.6 on 2019-11-01 15:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/insta'), upload_to='')),
            ],
        ),
    ]
